# Use node as the builder image
FROM swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/guergeiro/pnpm:18-9

# Maintainer information
MAINTAINER tanwenyang@aliyun.com

# Showing that port 3000 can be published
EXPOSE 3000

# Copy the oneimg file from the local directory to the /app directory inside the container
COPY . /app

# Change the working directory to /app
WORKDIR /app

# Building the html code
RUN pnpm install --registry=https://registry.npmmirror.com/

#Start server
CMD pnpm dev -H 0.0.0.0
