# Use node as the base image
FROM node:alpine

# Maintainer information
MAINTAINER tanwenyang@aliyun.com

# Showing that port 3000 can be published
EXPOSE 3000

# Copy the oneimg file from the local directory to the /app directory inside the container
COPY . /app

# Change the working directory to /app
WORKDIR /app

#Install pnpm
RUN npm install -g pnpm --registry=https://registry.npmmirror.com/

# Building the html code
RUN pnpm install --registry=https://registry.npmmirror.com/ && pnpm run build

#Start server
CMD pnpm run start  -H 0.0.0.0
