import type { ArticleModuleTemplate, CustomCSSProperties } from '@/types/template'

export const commonTypography: CustomCSSProperties = {
  '& :where(p)': {
    marginTop: '5px',
    marginBottom: '5px',
    lineHeight: 1.7,
  },
  '& :where(code)': {
    backgroundColor: 'var(--gray-2)',
    borderRadius: '0.4rem',
    color: 'var(--black)',
    fontSize: '0.85rem',
    padding: '0.25em 0.3em',
  },
  '& :where(pre)': {
    background: 'var(--black)',
    borderRadius: '0.5rem',
    color: 'var(--white)',
    fontFamily: 'JetBrainsMono, monospace',
    margin: '1.5rem 0',
    padding: '0.75rem 1rem',
    code: {
      background: 'none',
      color: 'inherit',
      fontSize: '0.8rem',
      padding: '0',
    },
  },
  '& :where(hr)': {
    border: 'none',
    borderTop: '1px solid var(--gray-2)',
    margin: '2rem 0',
  },
  '& :where(blockquote)': {
    borderLeft: '3px solid var(--gray-2)',
    margin: '1.5rem 0',
    paddingLeft: '1rem',
  },
  '& :where(img)': {
    display: 'block',
  },
  '& :where(ul)': {
    listStyleType: 'disc',
    paddingLeft: '1.625rem',
  },
  '& :where(ol)': {
    listStyleType: 'decimal',
    paddingLeft: '1.625rem',
  },
  '& :where(ul>li, ol>li)': {
    marginTop: '.75rem',
    marginBottom: '.75rem',
  },
  '& :where(ul ul, ol ul, ol ol, ul ol)': {
    marginTop: '.75rem',
    marginBottom: '.75rem',
  },
  '& [data-class="oneimg-images"]': {
    display: 'grid',
    rowGap: '0.5rem',
    gridTemplateColumns: 'repeat(1, minmax(0, 1fr))',
    marginTop: '5px',
    marginBottom: '5px',
  },
  '& :where(:first-child)': {
    marginTop: 0,
  },
  '& :where(:last-child)': {
    marginBottom: 0,
  },
}

export const baseTemplateStyle: ArticleModuleTemplate = {
  common: {
    container: {},
    title: {},
    content: commonTypography,
  },
  hero: {
    container: {
      fontFamily: 'unset',
      fontKerning: 'none',
      fontStyle: 'normal',
      fontSize: '22px',
      fontWeight: 400,
      fontSynthesis: 'none',
      color: '#333',
      contain: 'style',
      direction: 'ltr',
      height: 'auto',
      minHeight: '250px',
      padding: '16px',
      letterSpacing: 0,
      lineHeight: '1.2',
      overflow: 'visible',
      overflowWrap: 'break-word',
      tabSize: 4,
      textAlign: 'left',
      textIndent: 0,
      textSizeAdjust: 'none',
      textTransform: 'none',
      whiteSpace: 'normal',
      wordBreak: 'normal',
    },
    title: {
      fontFamily: 'unset',
      fontKerning: 'none',
      fontStyle: 'normal',
      fontSize: '22px',
      fontWeight: 400,
      fontSynthesis: 'none',
      color: '#333',
      contain: 'style',
      direction: 'ltr',
      height: 'auto',
      padding: '16px',
      letterSpacing: 0,
      lineHeight: '1.2',
      overflow: 'visible',
      overflowWrap: 'break-word',
      tabSize: 4,
      textAlign: 'left',
      textIndent: 0,
      textSizeAdjust: 'none',
      textTransform: 'none',
      whiteSpace: 'normal',
      wordBreak: 'normal',
    },
    content: {
      fontFamily: 'unset',
      fontKerning: 'none',
      fontStyle: 'normal',
      fontSize: '22px',
      fontWeight: 400,
      fontSynthesis: 'none',
      color: '#333',
      contain: 'style',
      direction: 'ltr',
      height: 'auto',
      padding: '16px',
      letterSpacing: 0,
      lineHeight: '1.2',
      overflow: 'visible',
      overflowWrap: 'break-word',
      tabSize: 4,
      textAlign: 'left',
      textIndent: 0,
      textSizeAdjust: 'none',
      textTransform: 'none',
      whiteSpace: 'normal',
      wordBreak: 'normal',

    },
  },
  main: {
    container: {
      fontFamily: 'unset',
      fontKerning: 'none',
      fontStyle: 'normal',
      fontSize: '18px',
      fontWeight: 400,
      fontSynthesis: 'none',
      color: '#333',
      contain: 'style',
      direction: 'ltr',
      height: 'auto',
      padding: 0,
      letterSpacing: 0,
      lineHeight: '1.2',
      overflow: 'visible',
      overflowWrap: 'break-word',
      tabSize: 4,
      textAlign: 'left',
      textIndent: 0,
      textSizeAdjust: 'none',
      textTransform: 'none',
      whiteSpace: 'normal',
      wordBreak: 'normal',
    },
    title: {
      fontFamily: 'unset',
      fontKerning: 'none',
      fontStyle: 'normal',
      fontSize: '18px',
      fontWeight: 400,
      fontSynthesis: 'none',
      color: '#333',
      contain: 'style',
      direction: 'ltr',
      height: 'auto',
      padding: 0,
      letterSpacing: 0,
      lineHeight: '1.2',
      overflow: 'visible',
      overflowWrap: 'break-word',
      tabSize: 4,
      textAlign: 'left',
      textIndent: 0,
      textSizeAdjust: 'none',
      textTransform: 'none',
      whiteSpace: 'normal',
      wordBreak: 'normal',
    },
    content: {
      fontFamily: 'unset',
      fontKerning: 'none',
      fontStyle: 'normal',
      fontSize: '18px',
      fontWeight: 400,
      fontSynthesis: 'none',
      color: '#333',
      contain: 'style',
      direction: 'ltr',
      height: 'auto',
      padding: 0,
      letterSpacing: 0,
      lineHeight: '1.2',
      overflow: 'visible',
      overflowWrap: 'break-word',
      tabSize: 4,
      textAlign: 'left',
      textIndent: 0,
      textSizeAdjust: 'none',
      textTransform: 'none',
      whiteSpace: 'normal',
      wordBreak: 'normal',
    },
  },
  sub: {
    container: {
      fontFamily: 'unset',
      fontKerning: 'none',
      fontStyle: 'normal',
      fontSize: '16px',
      fontWeight: 400,
      fontSynthesis: 'none',
      color: '#333',
      contain: 'style',
      direction: 'ltr',
      height: 'auto',
      padding: 0,
      marginTop: '15px',
      marginBottom: '15px',
      letterSpacing: 0,
      lineHeight: '1.2',
      overflow: 'visible',
      overflowWrap: 'break-word',
      tabSize: 4,
      textAlign: 'left',
      textIndent: 0,
      textSizeAdjust: 'none',
      textTransform: 'none',
      whiteSpace: 'normal',
      wordBreak: 'normal',
    },
    title: {
      fontFamily: 'unset',
      fontKerning: 'none',
      fontStyle: 'normal',
      fontSize: '16px',
      fontWeight: 400,
      fontSynthesis: 'none',
      color: '#333',
      contain: 'style',
      direction: 'ltr',
      height: 'auto',
      padding: 0,
      letterSpacing: 0,
      lineHeight: '1.2',
      overflow: 'visible',
      overflowWrap: 'break-word',
      tabSize: 4,
      textAlign: 'left',
      textIndent: 0,
      textSizeAdjust: 'none',
      textTransform: 'none',
      whiteSpace: 'normal',
      wordBreak: 'normal',
    },
    content: {
      fontFamily: 'unset',
      fontKerning: 'none',
      fontStyle: 'normal',
      fontSize: '16px',
      fontWeight: 400,
      fontSynthesis: 'none',
      color: '#333',
      contain: 'style',
      direction: 'ltr',
      height: 'auto',
      padding: 0,
      letterSpacing: 0,
      lineHeight: '1.2',
      overflow: 'visible',
      overflowWrap: 'break-word',
      tabSize: 4,
      textAlign: 'left',
      textIndent: 0,
      textSizeAdjust: 'none',
      textTransform: 'none',
      whiteSpace: 'normal',
      wordBreak: 'normal',
    },
  },
}
