import type { ArticleModuleTemplate } from '@/types'

export const techTemplate: ArticleModuleTemplate = {
  common: {
    container: {},
    title: {},
    content: {},
  },
  hero: {
    container: {
      position: 'relative',
      display: 'flex',
      flexDirection: 'column',
      justifyContent: 'center',
      paddingLeft: '12px',
      paddingTop: '13px',
      paddingRight: '12px',
      paddingBottom: '13px',
      textAlign: 'center',
      backgroundSize: 'cover',
      backgroundRepeat: 'no-repeat',
      backgroundColor: '#ccedff',
      backgroundImage: 'url(/images/them-bg-tech-blue.png)',
    },
    title: {
      position: 'relative',
      zIndex: 1,
      marginTop: '45px',
      marginBottom: '5px',
      fontWeight: 'bold',
      fontSize: '30px',
      color: '#333',
      textAlign: 'center',
    },
    content: {
      position: 'relative',
      zIndex: 2,
      fontSize: '18px',
    },

  },
  main: {
    container: {
      backgroundColor: '#ccedff',
      paddingLeft: '12px',
      paddingRight: '12px',
      paddingTop: '13px',
      paddingBottom: '13px',
    },
    title: {
      'position': 'relative',
      'marginBottom': '13px',
      'padding': '10px 19px',
      'fontSize': '19px',
      'fontWeight': 'bold',
      'lineHeight': '1.0',
      'color': '#fff',
      'backgroundImage': 'linear-gradient(90deg, #3CA0FF 0%, #1D6DFF 100%)',
      'borderRadius': '10px',
      '&::after': {
        content: '"NO." attr(data-index)',
        position: 'absolute',
        right: '19px',
        top: '50%',
        transform: 'translateY(-50%)',
        display: 'inline-block',
        marginLeft: '5px',
        color: 'rgb(255 255 255 / 0.2)',
      },
      'p': {
        marginRight: '45px',
      },
    },
    content: {
      position: 'relative',
      padding: '12px 18px',
      borderRadius: '12px',
      fontSize: '15px',
      backgroundColor: 'rgb(255 255 255 / 0.7)',
      color: '#333',
    },
  },
  sub: {
    container: {},
    title: {
      display: 'flex',
      alignItems: 'center',
      width: 'fit-content',
      marginBottom: '10px',
      lineHeight: '1.2',
      borderRadius: '9999px 9999px 9999px 2px',
      fontWeight: 'bold',
      padding: '8px 20px',
      fontSize: '17px',
      backgroundImage: 'linear-gradient(90deg, #3CA0FF 0%, #1D6DFF 100%)',
      color: '#fff',
      p: {
        lineHeight: 'inherit',
        margin: 0,
      },
    },
    content: {},
  },
}
