import type { ArticleModuleTemplate } from '@/types'

export const cartoonTemplate: ArticleModuleTemplate = {
  common: {
    container: {},
    title: {},
    content: {},
  },
  hero: {
    container: {
      'position': 'relative',
      'display': 'flex',
      'flexDirection': 'column',
      'justifyContent': 'center',
      'paddingLeft': '12px',
      'paddingTop': '13px',
      'paddingRight': '12px',
      'paddingBottom': '13px',
      'textAlign': 'center',
      'backgroundSize': 'cover',
      'backgroundRepeat': 'no-repeat',
      'color': 'var(--hero-container-foreground)',
      'backgroundColor': 'var(--hero-container-background)',

      '&::before': {
        content: '""',
        position: 'absolute',
        width: '110px',
        height: '110px',
        top: '15px',
        left: 0,
        backgroundImage: 'var(--hero-container-background-image-left)',
        backgroundRepeat: 'no-repeat',
      },

      '&::after': {
        content: '""',
        position: 'absolute',
        width: '80px',
        height: '80px',
        right: '20px',
        top: '50%',
        backgroundImage: 'var(--hero-container-background-image-right)',
        backgroundRepeat: 'no-repeat',
      },
    },
    title: {
      'position': 'relative',
      'fontWeight': 700,
      'fontSize': '36px',
      'fontFamily': 'var(--font-zcool-kuailve)',
      'WebkitTextStroke': '1px #000',
      'color': 'var(--hero-title-foreground)',
      'backgroundColor': 'var(--hero-title-background)',

      '& p': {
        paddingLeft: '24px',
        paddingRight: '24px',
      },

      '&::before': {
        content: '""',
        position: 'absolute',
        width: '24px',
        height: '24px',
        top: '-10px',
        left: '10px',
        backgroundSize: '24px 24px',
        backgroundImage: 'url(/images/cartoon-star-yellow.svg)',
        backgroundRepeat: 'no-repeat',
      },

      '&::after': {
        content: '""',
        position: 'absolute',
        width: '24px',
        height: '24px',
        right: '20px',
        bottom: 0,
        backgroundImage: 'url(/images/cartoon-star-yellow.svg)',
        backgroundRepeat: 'no-repeat',
        backgroundPosition: 'center',
        backgroundSize: '18px 18px',
      },
    },
    content: {
      'color': 'var(--hero-content-foreground)',
      'backgroundColor': 'var(--hero-content-background)',
      'fontSize': '19px',
      ':where(p)': {
        marginTop: '18px',
        marginBottom: '18px',
      },
      ':where(:first-child)': {
        marginTop: 0,
      },
      ':where(:last-child)': {
        marginBottom: 0,
      },
    },
  },
  main: {
    container: {
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      padding: '16px',
      color: 'var(--main-container-foreground)',
      backgroundColor: 'var(--main-container-background)',
    },
    title: {
      'position': 'relative',
      'display': 'inline-flex',
      'justifyContent': 'center',
      'padding': '4px 24px',
      'marginBottom': '-20px',
      'fontFamily': 'var(--font-zcool-kuailve)',
      'fontSize': '24px',
      'fontWeight': 700,
      'lineHeight': 1.2,
      'borderRadius': '9999px',
      'border': '1px solid',
      'backgroundColor': 'var(--main-title-background-secondary)',
      'zIndex': 1,

      '&::before': {
        content: '""',
        position: 'absolute',
        top: -2,
        left: 0,
        right: 0,
        height: '100%',
        backgroundColor: 'var(--main-title-background-primary)',
        border: '1px solid',
        borderRadius: '9999px',
        zIndex: -1,
      },

      '&::after': {
        content: '""',
        position: 'absolute',
        width: '24px',
        height: '24px',
        right: '-10px',
        bottom: '-8px',
        backgroundImage: 'url(/images/cartoon-direction-icon.svg)',
        backgroundRepeat: 'no-repeat',
        zIndex: 2,
      },
    },
    content: {
      width: '100%',
      paddingTop: '30px',
      paddingLeft: '16px',
      paddingRight: '16px',
      paddingBottom: '15px',
      fontSize: '15px',
      borderRadius: '8px',
      border: '1px solid',
      backgroundColor: 'var(--main-content-background)',
    },
  },
  sub: {
    container: {},
    title: {
      'maxWidth': 'fit-content',
      'padding': '4px 18px',
      'lineHeight': '20px',
      'fontWeight': 700,
      'fontSize': '20px',
      'fontFamily': 'var(--font-zcool-kuailve)',
      'backgroundColor': 'var(--sub-title-background)',
      'borderTopLeftRadius': '9999px',
      'borderTopRightRadius': '9999px',
      'borderBottomRightRadius': '9999px',
      'borderBottomLeftRadius': '4px',
      'border': '1px solid',
      '& p': {
        margin: 0,
        lineHeight: 'inherit',
      },
    },
    content: {
      color: 'var(--sub-content-foreground)',
    },
  },
}
